// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lznebwyfnprnlwndewec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6bmVid3lmbnBybmx3bmRld2VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5OTUzMjcsImV4cCI6MjA1MTU3MTMyN30.YWCJUZPpFN9CuGAaRI58kdVUdTi3_V-Sdbrrh4p-pGs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);